# Полезные ссылки

https://www.itproger.com/course/python 
Python для начинающих. Достаточно неплохо изложены базовый материал, но лучше применять Jupyter Notebook в качестве оболочки.быстрого ИМХО. Из плюсов: просто и быстро

https://www.youtube.com/watch?v=EHVmseAhkx0 Основы матанализа для Data Science. Что важно знать из матана в интеллектуальном анализе данных (Middle Senior). Без лишней воды, просто и быстро

# Работа с массивами данных

Массивы - это структура данных, хранящая набор значений (элементов массива), идентифицируемых по индексу или набору индексов, принимающих целые (или приводимые к целым) значения из некоторого заданного непрерывного диапазона:

Массив данных может быть отображен в качестве одной переменной. Размерность массива — это количество индексов, необходимое для однозначной адресации элемента в рамках массива[1][2]. По количеству используемых индексов массивы делятся на одномерные, двумерные.

ОДНОМЕРНЫЕ МАССИВЫ:

In [41]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

 dtype - аргумент, при помощи которого формируется десятичные цифры

In [45]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.float64)
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

ДВУМЕРНЫЕ МАССИВЫ:

Двумерные массивы должны иметь одинаковую длину и выделяться синтаксисом:

In [51]:
a = np.array([[1, 2, 3, 4, 5],
              [5, 6, 7, 8, 9]], dtype=float)
a

array([[1., 2., 3., 4., 5.],
       [5., 6., 7., 8., 9.]])

# Атрибуты массива

Массивы данных служат для ускорения работы с данными. Наряду со списками, кортежами и строками. Похожи на списки, но с ограничением по:
- dtype - типу данных
- shape - размеру элементов
Атрибуты массивов: 
- shape - размер массива по горизонтали и вертикали в символах;
- ndim - количество размерностей;
- dtype - возвращает к исходному формату, хранящегося в текущей сессии

In [52]:
a.shape

(2, 5)

In [53]:
a.ndim

2

In [54]:
a.dtype

dtype('float64')

При помощи функции astype Вы можете сконвертировать массив (указать тип массива) 

In [55]:
a.astype(int)

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

# Размерность массивов и хранение

ИЗМЕНЕНИЕ ФОРМЫ МАССИВА

Массивы в библиотеке хранятся в строгой заданной последовательности, как единый большой кусок данных. Поэтому изменение последовательности просто указывает: где начинается / заканчивается строка.

In [66]:
a

array([[1., 2., 3., 4., 5.],
       [5., 6., 7., 8., 9.]])

Вместе с атрибутами типа (dtype) и размера (shape)...

In [61]:
a.dtype

dtype('float64')

... атрибут strides показывает, насколько байтов необходимо отступить прежде чем перейти к следующему элементу в строке или в столбце. 

In [57]:
a.strides

(40, 8)

Размер 1-го числа = 8 байт. В строке 5 чисел. Следовательно размер строки из 5 чисел равен 8*5=40 байт:

In [58]:
a.dtype.itemsize

8

Для того, чтобы изменить параметры массива и сделать другую геометрию куска, достаточно изменить форму (shape) и размерность в байтах (straids). Это можно сделать при помощи оператора (reshape):

In [64]:
b = a.reshape(5,2)
b

array([[1., 2.],
       [3., 4.],
       [5., 5.],
       [6., 7.],
       [8., 9.]])

теперь длина строки составляет 8*2=16 байтов

In [65]:
b.strides

(16, 8)

КАК ВЫТЯНУТЬ МАССИВ В ОДНУ СТРОЧКУ

Метод flaven: в массиве "b" значение оставляем, в "a" меняем на [0, 1]

In [67]:
b = a.flatten()
a[0, 1] = -20

b

array([1., 2., 3., 4., 5., 5., 6., 7., 8., 9.])

In [ ]:
Метод ravel: в отличие от flatten не оставлояет копию

In [68]:
b = a.ravel()
a[0, 1] = -30

b

array([  1., -30.,   3.,   4.,   5.,   5.,   6.,   7.,   8.,   9.])

# СОЗДАНИЕ МАССИВОВ

Массивы - это структура данных, хранящая набор значений (элементов массива), идентифицируемых по индексу или набору индексов, принимающих целые (или приводимые к целым) значения из некоторого заданного непрерывного диапазона:

Массив данных может быть отображен в качестве одной переменной. Размерность массива — это количество индексов, необходимое для однозначной адресации элемента в рамках массива[1][2]. По количеству используемых индексов массивы делятся на одномерные, двумерные, трёхмерные и т. д

ОДНОМЕРНЫЕ МАССИВЫ:

In [41]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

 dtype - аргумент, при помощи которого формируется десятичные цифры

In [45]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.float64)
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

ДВУМЕРНЫЕ МАССИВЫ:

Двумерные массивы должны иметь одинаковую длину и выделяться синтаксисом:

In [51]:
a = np.array([[1, 2, 3, 4, 5],
              [5, 6, 7, 8, 9]], dtype=float)
a

array([[1., 2., 3., 4., 5.],
       [5., 6., 7., 8., 9.]])

# Атрибуты массива

Массивы данных служат для ускорения работы с данными. Наряду со списками, кортежами и строками. Похожи на списки, но с ограничением по:
- dtype - типу данных
- shape - размеру элементов
Атрибуты массивов: 
- shape - размер массива по горизонтали и вертикали в символах;
- ndim - количество размерностей;
- dtype - возвращает к исходному формату, хранящегося в текущей сессии

In [52]:
a.shape

(2, 5)

In [53]:
a.ndim

2

In [54]:
a.dtype

dtype('float64')

При помощи функции astype Вы можете сконвертировать массив (указать тип массива) 

In [55]:
a.astype(int)

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

# Размерность массивов и хранение

ИЗМЕНЕНИЕ ФОРМЫ МАССИВА

Массивы в библиотеке хранятся в строгой заданной последовательности, как единый большой кусок данных. Поэтому изменение последовательности просто указывает: где начинается / заканчивается строка.

In [66]:
a

array([[1., 2., 3., 4., 5.],
       [5., 6., 7., 8., 9.]])

Вместе с атрибутами типа (dtype) и размера (shape)...

In [61]:
a.dtype

dtype('float64')

... атрибут strides показывает, насколько байтов необходимо отступить прежде чем перейти к следующему элементу в строке или в столбце. 

In [57]:
a.strides

(40, 8)

Размер 1-го числа = 8 байт. В строке 5 чисел. Следовательно размер строки из 5 чисел равен 8*5=40 байт:

In [58]:
a.dtype.itemsize

8

Для того, чтобы изменить параметры массива и сделать другую геометрию куска, достаточно изменить форму (shape) и размерность в байтах (straids). Это можно сделать при помощи оператора (reshape):

In [64]:
b = a.reshape(5,2)
b

array([[1., 2.],
       [3., 4.],
       [5., 5.],
       [6., 7.],
       [8., 9.]])

теперь длина строки составляет 8*2=16 байтов

In [65]:
b.strides

(16, 8)

КАК ВЫТЯНУТЬ МАССИВ В ОДНУ СТРОЧКУ

Метод flaven: в массиве "b" значение оставляем, в "a" меняем на [0, 1]

In [67]:
b = a.flatten()
a[0, 1] = -20

b

array([1., 2., 3., 4., 5., 5., 6., 7., 8., 9.])

# Транспонирование массивов

Транспонирование массива = замена строчек столбцами и наоборот с сохранением последовательности всех элементов. Дважды транспонированная матрица = исходному массиву.   

In [74]:
c = a.T
a[0, 1] = -40

c

array([[  1.,   5.],
       [-40.,   6.],
       [  3.,   7.],
       [  4.,   8.],
       [  5.,   9.]])

Если размерностей несколько и соответственно несколько осей, то менять нужно сразу две попарно

Arange () - это функция, используемая для получения равномерно распределенных значений в заданном интервале. Значения генерируются в пределах полуоткрытого интервала [start, stop]

In [80]:
b = np.arange(10)

b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Метод np.newaxis создает новый вектор:

In [81]:
b[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

Метод np.expand_dims позволяет добавить размерность:

In [83]:
np.expand_dims(b, axis=0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
... таким же обрахом возвращаем обратно вектор в столбец

In [86]:
b[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [85]:
b[np.newaxis, :, np.newaxis].shape

(1, 10, 1)

Эти опции необходимы для соблюдения соразмерности массивов при выполнении математических операций, вычислений в python

# Массивы с особыми свойствами

Для создания массивов в бинарном коде (0 и 1) удобно применять функции 
- zeros (создание массивов из нулей)
- ones (создание массивов из единиц)
Создадим матрицу из нулей со сторонами 3 и 2:

In [88]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [89]:
np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Для создания соразмерных массивов применяем оператор like

In [90]:
np.ones_like(a)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
np.zeros_like(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Для создания "коробочных" массивов с диагональю из единиц применяем оператор "eye" (Для решения уравнений методом Гауса):

In [95]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Оператор arange создает последовательность элементов. Например от 1 до 10 c шагом 2 (Полезно при использовании численных методов Фибоначчи):

In [100]:
np.arange(1, 10, 3)

array([1, 4, 7])

При помощи оператора 'linspace' можно разбить взятый векторный массив на несколько равных интервалов: 

In [101]:
np.linspace(0, 1, 6, endpoint=True)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

# Array и Asarray

Создание нескольких компилируемых массивов осуществляется при помощи функций:
- array - создает массив с копией в переменной, например 'a'
- asarray возвращает объект массив, прикрепленный к переменной 'a'.

Для начала задаем массив 'a'

In [110]:
a=np.array([1, 2, 3, 4, 5, 6, 7], dtype=np.float64)
b=np.asarray(a)
c=np.array(a)

b, c

(array([1., 2., 3., 4., 5., 6., 7.]), array([1., 2., 3., 4., 5., 6., 7.]))

... и проверяем путем замены одной из переменных в массиве 'a' (порядковые номера в [] начинаются с 0)

In [130]:
a[0] = 0

b, c

... таким образом в массиве 'b', который создавали при помощи (asarray) изменилась первая переменная, в массиве 'c' (array) весь ряд остался без изменений 

# ОСНОВНЫЕ ОПЕРАЦИИ С МАССИВАМИ

# Унарные операции со скалярными величинами
Скалярная величина equal статическая величина (НЕ векторная)
С массивами данных можно выполнять аналогичные математические преобразования, как и с целыми числами. 

In [228]:
a = np.arange(10).reshape(2, -1) #создаем массив
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Возведение в степень:

In [146]:
a ** 3 # например в куб

array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]], dtype=int32)

Умножение и сложение:

In [140]:
a * 2 # умножение

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [145]:
2 + a # сложение

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

Извлечение квадратного корня:

In [147]:
np.sqrt(a) # квадратный корень

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

Возведение в степень:

In [234]:
a = np.arange(10).reshape(2, -1) #создаем массив
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [235]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

Взятие логарифмов:

In [231]:
a[0] = 1

In [158]:
np.log(1 * a) # обычный логарифм

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458]])

In [159]:
np.log2(1 * a) # двоичный логарифм

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ]])

In [236]:
a > 1 # сравнение (булевая логика)

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Агрегирующие операции
При помощи данных операций можно производить вычисления с несколькими массивами данных. Для начала создадим случайный массив при помощи функции 'np.random.seed'

In [183]:
import random #генератор случайных чисел

In [210]:
a = np.arange(25).reshape(5, -1) #создаем массив
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

...и выведем основные функции: 

In [211]:
a.min(), a.max(), a.argmax(), a.sum(), a.prod(), a.mean()

(0, 24, 24, 300, 0, 12.0)

# Операции с массивами по осям (x,y)

a.agg(axis*axis) 
axis=0 - это всегда Y
axis=1 - это всегда X

In [7]:
a = np.arange(25).reshape(5, -1) # составляем двумерный массив
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Задача A:
1). Необходимо узнать max значение по столбцам - по значению 'y' (axis0)
2). Необходимо узнать min значение по строкам - по значению 'x' (axis1)
Решение:

In [223]:
a.max(axis=0) #редукция вдоль оси Y axis=0 (=max по столбцам)

array([20, 21, 22, 23, 24])

In [237]:
a.min(axis=1) #дедукция вдоль оси X axis=1 (=min по строкам)

array([0, 5])

# Задача B:
Найти суммы всех "горизонталей" и "вертикалей:

In [225]:
a.sum(axis=1) #суммирование всех значение вдоль оси X axis=1 (горизонтьаль)

array([ 10,  35,  60,  85, 110])

In [226]:
a.sum(axis=0) #суммирование всех значение вдоль оси Y axis=0 (вертикаль)

array([50, 55, 60, 65, 70])

# Задача С
Найти индекс (аргумент) максимального значения argmax

In [14]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
a.argmax()

24

# Задача D
Узнать какую задачу решает данная функция

In [13]:
i = np.argmax(a)
i, j = i // a.shape[1], 1 % a.shape[1] 

print("value =", a[i, j])
print("index =", [i, j])

value = 21
index = [4, 1]


In [18]:
np.unravel_index(np.argmax(a), a.shape)

(4, 4)

Сравнение скоростей выполнения функций при помощи библиотеки Nympy и выполнения той же функции путем базовой команды Python: 
1). Создаем массив:

In [19]:
b = np.random.randint(0, 10, size=(1_000, 1_000))
b[30, 42] = 20
b = b.ravel()

скорость выполнения при помощи Numpy:

In [20]:
%%timeit #оператор замера скорости выполнения команды

b.max()

824 µs ± 51.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
та же функция вызванная базовой командой Python:

In [21]:
%%timeit

max(b)

69.5 ms ± 2.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Ка мы видим скорость выполнения команды mx(b) ниже. Это связано с тем, что сначала программа обращается к списку b, выполняет внутренний алгоритм 'for', а уже затем вычисляет max из списка данных. 

# Унарные операции над булевыми массивами

- any - возвращает массив, если есть хотя бы один элемент (true)
- all - возвращает массив, если все эллементы соответствуют выбранному критерию

In [23]:
a = np.asarray([True, True, False, False, True])
a

array([ True,  True, False, False,  True])

In [24]:
a.any(), np.any(a), any(a) #одна и таже функция, выполняемая двумя разными способами. Первый вариант предпочтительнее

(True, True, True)

In [28]:
a.all(), np.all(a), all(a) #одна и таже функция, выполняемая двумя разными способами. Первый вариант предпочтительнее

(False, False, False)

In [32]:
a = np.asarray([[True, True, False, False, True], 
               [True, False, False, True, False]])
a

array([[ True,  True, False, False,  True],
       [ True, False, False,  True, False]])

- logical_not инвертирует булевые массивы обратно в исходное состояние:

In [33]:
np.logical_not(a)

array([[False, False,  True,  True, False],
       [False,  True,  True, False,  True]])

In [35]:
~a

array([[-2, -2, -1, -1, -2],
       [-2, -1, -1, -2, -1]], dtype=int32)

# Домашнее задание:
- Составить двумерные равноразмерные массивы кратные 3-м
- Провести вычисления сумм "вертикальных" и "горизонтальных" полей
- Найти закономерности